name: "Doxygen"

on:
  push:
    branches:
      - stable

env:
  DOXYGEN_VERSION: 1.9.3

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@v3.18.3

      - name: Update packages
        shell: bash
        run: sudo apt update

      - name: Install Doxygen
        shell: bash
        run: |
          mkdir doxy-bin && cd doxy-bin
          wget https://sourceforge.net/projects/doxygen/files/rel-${{env.DOXYGEN_VERSION}}/doxygen-${{env.DOXYGEN_VERSION}}.src.tar.gz/download
          tar xf download
          cd doxygen-${{env.DOXYGEN_VERSION}}
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j $(nproc)
          sudo make install

      - name: Generate Doxygen output
        shell: bash
        run: doxygen

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.2
        with:
          branch: gh-pages
          folder: doxygen-out/html