name: "CI: macOS"

on: [ push, pull_request ]

env:
  MIX_VERSION: 2.0.4

jobs:
  macos-test:
    runs-on: macos-latest
    strategy:
      matrix:
        CPP_VERSION: [ 17, 20 ]
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Install mpg123
        shell: bash
        run: brew install mpg123

      - name: Install OpenGL
        shell: bash
        run: brew install glfw

      - name: Install SDL2
        shell: bash
        run: brew install SDL2

      - name: Install SDL2_image
        shell: bash
        run: brew install SDL2_image

      # Due to some unfortunate default options in the brew formula, we install SDL2_mixer manually
      - name: Install SDL2_mixer
        shell: bash
        run: |
          curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-${{env.MIX_VERSION}}.tar.gz | tar xz
          cd SDL2_mixer-${{env.MIX_VERSION}}
          ./configure
          make
          make install

      - name: Install SDL2_ttf
        shell: bash
        run: brew install SDL2_ttf

      - name: Make build directory
        shell: bash
        run: mkdir build

      - name: Build
        working-directory: ./build
        shell: bash
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{matrix.CPP_VERSION}} -GNinja
          ninja

      - name: Run unit tests
        working-directory: ./build/test/unit-tests
        shell: bash
        run: ./CenturionTests

      - name: Run mocked test suite
        working-directory: ./build/test/mocks
        shell: bash
        run: ./CenturionMocks
