name: CI (Windows with MSVC)

on: [push, pull_request]

env:
  SDL_VERSION: 2.0.14
  IMG_VERSION: 2.0.5
  MIX_VERSION: 2.0.4
  TTF_VERSION: 2.0.15

jobs:
  windows-latest-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Create binaries directory
        run: mkdir bin
        shell: cmd

      - name: Download SDL2
        uses: albin-johansson/download-sdl2@v1
        with:
          version: ${{env.SDL_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_image
        uses: albin-johansson/download-sdl2-image@v0.1
        with:
          version: ${{env.IMG_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_mixer
        uses: suisei-cn/actions-download-file@v1
        id: DownloadSDL2_mixer
        with:
          url: "https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-${{env.MIX_VERSION}}-VC.zip"
          target: .

      - name: Download SDL2_ttf
        uses: suisei-cn/actions-download-file@v1
        id: DownloadSDL2_ttf
        with:
          url: "https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-${{env.TTF_VERSION}}-VC.zip"
          target: .

      - name: Download SDL2_mixer runtime binaries
        uses: suisei-cn/actions-download-file@v1
        id: download_sdl2_mixer_runtime_binaries
        with:
          url: "https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-${{env.MIX_VERSION}}-win32-x64.zip"
          target: ./bin

      - name: Download SDL2_ttf runtime binaries
        uses: suisei-cn/actions-download-file@v1
        id: download_sdl2_ttf_runtime_binaries
        with:
          url: "https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-${{env.TTF_VERSION}}-win32-x64.zip"
          target: ./bin

      - name: Unzip archives (sources)
        run: |
          7z x -y SDL2_mixer-devel-${{env.MIX_VERSION}}-VC.zip
          7z x -y SDL2_ttf-devel-${{env.TTF_VERSION}}-VC.zip

      - name: Unzip archives (runtime binaries)
        run: |
          7z e -y ./bin/SDL2_mixer-${{env.MIX_VERSION}}-win32-x64.zip -obin
          7z e -y ./bin/SDL2_ttf-${{env.TTF_VERSION}}-win32-x64.zip -obin

      - name: Create build folder
        run: cmake -E make_directory ./build

      - name: Build
        working-directory: ./build
        env:
          SDL2DIR: ${{github.workspace}}/SDL2-${{env.SDL_VERSION}}
          SDL2IMAGEDIR: ${{github.workspace}}/SDL2_image-${{env.IMG_VERSION}}
          SDL2MIXERDIR: ${{github.workspace}}/SDL2_mixer-${{env.MIX_VERSION}}
          SDL2TTFDIR: ${{github.workspace}}/SDL2_ttf-${{env.TTF_VERSION}}
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja

      - name: Run mocked test suite
        working-directory: ./build/test/mocks
        run: CenturionMocks
        shell: cmd