name: "CI: Windows"

on: [ push, pull_request ]

env:
  IMG_VERSION: 2.0.5
  MIX_VERSION: 2.0.4

jobs:
  windows-latest-test:
    runs-on: windows-latest
    strategy:
      matrix:
        SDL_VERSION: [ 2.0.10, 2.0.12, 2.0.14, 2.0.16, 2.0.18, 2.0.20 ]
        TTF_VERSION: [ 2.0.15 ]
        CPP_VERSION: [ 17, 20 ]
        include:
          - SDL_VERSION: 2.0.18
            TTF_VERSION: 2.0.18
            CPP_VERSION: 20

          - SDL_VERSION: 2.0.20
            TTF_VERSION: 2.0.18
            CPP_VERSION: 20

          - SDL_VERSION: 2.0.20
            TTF_VERSION: 2.0.18
            CPP_VERSION: 23
    steps:
      - uses: actions/checkout@main
      - uses: ilammy/msvc-dev-cmd@master
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: lukka/get-cmake@latest

      - name: Create binaries directory
        shell: cmd
        run: mkdir bin

      - name: Download SDL2
        uses: albin-johansson/download-sdl2@latest
        with:
          version: ${{matrix.SDL_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_image
        uses: albin-johansson/download-sdl2-image@latest
        with:
          version: ${{env.IMG_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_ttf
        uses: albin-johansson/download-sdl2-ttf@latest
        with:
          version: ${{matrix.TTF_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_mixer
        uses: albin-johansson/download-sdl2-mixer@latest
        with:
          version: ${{env.MIX_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Create build folder
        run: cmake -E make_directory ./build

      - name: Build
        working-directory: ./build
        env:
          SDL2DIR: ${{github.workspace}}/SDL2-${{matrix.SDL_VERSION}}
          SDL2IMAGEDIR: ${{github.workspace}}/SDL2_image-${{env.IMG_VERSION}}
          SDL2MIXERDIR: ${{github.workspace}}/SDL2_mixer-${{env.MIX_VERSION}}
          SDL2TTFDIR: ${{github.workspace}}/SDL2_ttf-${{matrix.TTF_VERSION}}
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{matrix.CPP_VERSION}} -GNinja
          ninja

      - name: Run mocked test suite
        shell: cmd
        working-directory: ./build/test/mocks
        run: mockcenturion
